### ISSUE TITLE
myImportJointFields does not appear to exist?

### ISSUE THREAD

**Issue by mreid2005** [sayuga/SerenityTutorials#1]
I've really been confounded by this particular entry. 

In myModuleImportEndpoint.cs
it references
` using jImpHelp = myImportJointFields.ExcelImportHelper;`

unless I'm being completely obtuse, myImportJointFields does not exist within myImportHelper.cs, or myImportFields.cs?  
Any insights would be appreciated.

**Comment by sayuga** [comment]
Ahh yes. That is a typo on my end. I renamed that file to myImportFields.cs ill update the documentation shortly. 

Essentially the helper file has the generics and the fields file manages the hamdling of field types.

**Comment by mreid2005** [comment]
Awesome thank you for taking a look!

**Comment by sayuga** [comment]
anytime. That's what I started this repository for after all.
