### ISSUE TITLE
Going through the tutorial and running into issues

### ISSUE THREAD

**Issue by mreid2005** [sayuga/SerenityTutorials#2]
I've tried running through the tutorial and getting this to work, and there are some oddities that keep hitching me up.

the use of Default for example.
also without BasicSamples installed a couple of service files that the example depends on aren't available to work with as examples.  that took me over a day to figure out why ExcelImportForm was throwing errors in the ImportDialog.ts

To try and work through my lack of knowledge for learning purposes I started a new project put the files into place and tried to line it up against the Northwind Customer module and still have red lines all over the place, throughout the implementation, after carefully replacing any "myModule" and myProject" and attempting to follow the tutorial exactly without deviation.

What other tutorials need to be done first in order for this to work? 

do you have a working Sample that works on the NorthWind Customer or Product database that can be used for reference while working through the tutorials using the template files?

I'd be happy to use A working sample along with the template code to provide insights into areas that could use more clarity.

thanks,
Michael

**Comment by sayuga** [comment]
Well, I originally set these files as sample outputs for the Excel Wiki I created for serenity. additionally, this is an "extension" of the excel import sample that is already present in serenity so it assumes that the person implementing it has already ran through the original excel import sample. I guess I shouldn't assume this though. I'll revisit the tutorial and add better reference that you should implement the Import sample from the original Serenity samples and then implement the extension. I'll also try to get you a working sample in the next day or two.

**Comment by mreid2005** [comment]
okay. that helps.
