### ISSUE TITLE
eMessage3 is undefined - 

### ISSUE THREAD

**Issue by mreid2005** [sayuga/SerenityTutorials#4]
Are we supposed to create our own handler for this or is this a bug.

`myErrors.Add(myImpHelp.eMessage3(row, ex.Message));`

in myModuleExcelImportEndpoint.cs
intellisense shows eMessage3 is not defined.

**Comment by sayuga** [comment]
I really need to be more thorough when cleaning my code. I apologize. you are welcome to use your own handler. What I had done, and is currently not present in the file, is I moved my error messages into it's own file.  That was meant to read: 

/// <summary>
        ///  Warning Message that field was not found, thus was added
        /// </summary>
        /// <param name="x">Row Number</param>
        /// <param name="y"> Field Name</param>
        /// <returns>Edited Message</returns>
        public static string eMessage(int x, string y)
        {            
            return "Warning: On Row " + x + ": Entity with name " + y + " was not found so it was added!"; //let the user know message;
        }

        /// <summary>
        /// Warning that Cascaded fields were not found, thus were added
        /// </summary>
        /// <param name="x">Row number</param>
        /// <param name="y">First Field Name</param>
        /// <param name="z">Secondary Field Name</param>
        /// <returns>Edited Message</returns>
        public static string eMessage4(int x, string y, string z)
        {
            return "Warning: On Row " + x + ": Entity with name " + y + " and sub-name " + z + " was not found so it was added!"; //let the user knowmessage;
        }

        /// <summary>
        /// IOException Message
        /// </summary>
        /// <param name="x">Row Number</param>
        /// <param name="y">Field Name</param>
        /// <param name="z">System Error Message</param>
        /// <returns>Edited Message</returns>
        public static string eMessage2(int x, string y, string z)
        {

            return "IOException for " + y + " Field for row " + x + " : " + z; //let the user knowmessage;
        }

        /// <summary>
        /// Exception message  
        /// </summary>
        /// <param name="x">Row Number </param>
        /// <param name="y">Indexed Column Number</param>
        /// <param name="z">System Exception Message</param>
        /// <returns>Edited Message</returns>
        public static string eMessage3(int x, int y, string z)
        {

            return "Exception on Row " + x + ", Index Column " + y + ": " + z; //let the user know//message;
        }

**Comment by mreid2005** [comment]
Thank you, that's a big help.  I'm unfortunately in the realm of I don't know what I don't know.  So when I see certain things I'm just not sure how they relate.
